---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "程序员导航"
subtitle: "【神引篇】九秘中二版"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"


links:
  - name: "[临]计算机基础"
    url: "#"
  - name: "[兵]工具技巧"
    url: "#page-tools" 
  - name: "[斗]模型法则"
    url: "#page-model" 
  - name: "[者]Java服务"
    url: "#page-service" 
  - name: "[皆]Web前端"
    url: "#page-ui" 
  - name: "[数]Python分析"
    url: "#page-data" 
  - name: "[组]技术浪潮"
    url: "#page-cstech" 
  - name: "[前]思维火花"
    url: "#page-thought" 
  - name: "[行]兴趣爱好"
    url: "#page-hobby" 


# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "[0-1]计算机科学"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-2]编程语言"
    icon: "fas fa-cloud"
    items:
      - name: "tiobe编程语言排行"
        logo: "assets/tools/sample.png"
        subtitle: "tiobe编程语言排行"
        tag: "app"
        url: "https://www.tiobe.com/tiobe-index/"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-3]硬件"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-4]软件"
    icon: "fas fa-cloud"
    items:
      - name: "github"
        logo: "https://luo0412.oss-cn-hangzhou.aliyuncs.com/1654600482555-cpEsr5fxGYa3.png"
        subtitle: "全球最大同性交友网站"
        tag: 
          - "git"
          - "开源"
        url: "https://github.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "gitee"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "https://gitee.com/"
        target: "_blank" # optional html a tag target attribute


  - name: "[0-5]操作系统"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-6]数据库"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-7]图形学"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-8]计算机网络"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute

  - name: "[0-9]密码学与安全攻防"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app222"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute